type Asset = {
  id: string;
  category: string;
  description: string | null;
  image_url: string | null;
};

export function ReferenceGallery({ assets }: { assets: Asset[] }) {
  if (!assets.length) {
    return <div className="status warning">No approved reference photographs are available.</div>;
  }

  return (
    <div className="gallery">
      {assets.map((asset) => (
        <article className="photo-card" key={asset.id}>
          {asset.image_url ? (
            // Signed URLs are short-lived and generated by an authenticated server route.
            // eslint-disable-next-line @next/next/no-img-element
            <img src={asset.image_url} alt={`${asset.category}: ${asset.description ?? "reference photo"}`} />
          ) : (
            <div className="photo-placeholder">{asset.category}<br />Photo placeholder</div>
          )}
          <div className="photo-caption">
            <div className="photo-category">{asset.category}</div>
            {asset.description ? <div className="muted">{asset.description}</div> : null}
          </div>
        </article>
      ))}
    </div>
  );
}
